apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: jupyter-eoepca-rbac
subjects:
  - kind: ServiceAccount
    name: hub
    namespace: jupyter-bla
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
